import Link from "next/link"
import Image from "next/image"
import Head from "next/head"
import Header from "../components/header"
import Slider from "react-slick"
import CourseItem from "../components/course-item"
import sales_1 from "../public/sales-1.jpeg"
import sales_2 from "../public/sales-2.jpeg"
import sales_3 from "../public/sales-3.jpeg"

import {
  Carousel,
  CarouselIndicators,
  CarouselItem,
  CarouselCaption,
  CarouselControl,
  Col,
  Collapse,
  Container,
  Card,
  CardHeader,
  CardImg,
  CardBody,
  CardText,
  UncontrolledDropdown,
  Button,
  Row,
  DropdownToggle,
  DropdownMenu,
  DropdownItem
} from "reactstrap"

import styles from "../styles/Home.module.css"

export default function Home() {
  const lastCourses = {
    arows: false,
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 3.5,
    slidesToScroll: 1,
    initialSlide: 0,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 2.5,
          slidesToScroll: 1,
          dots: true
        }
      },
      {
        breakpoint: 768,
        settings: {
          arows: false,
          slidesToShow: 2,
          slidesToScroll: 2
        }
      },
      {
        breakpoint: 480,
        settings: {
          arows: false,
          slidesToShow: 1,
          slidesToScroll: 1
        }
      }
    ]
  }

  const specialOffer = {
    arows: false,
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 3,
    slidesToScroll: 1,
    initialSlide: 0,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          dots: true
        }
      },
      {
        breakpoint: 768,
        settings: {
          mode: 'center',
          arows: false,
          slidesToShow: 2,
          slidesToScroll: 2
        }
      },
      {
        breakpoint: 480,
        settings: {
          arows: false,
          slidesToShow: 1,
          slidesToScroll: 1
        }
      }
    ]
  }

  return (
    <div>
      <Head>
        <title>Школа косметологии</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <div className="mb-5 mt-5" style={{ height: "90px" }}></div>
      
      <section className="section--last-courses container-md mt-5 mb-5 pb-5">
        <Row>
          <h2 className="text-center mb-5">Ближайшее обучение</h2>
          <Slider {...lastCourses}>
            <div>
              <CourseItem type="card-type--offline"
                          subtitle="Курс косметологии"
                          title="Курс косметик - эстетист"
                          typeName="Оффлайн"
                          dateStart="1 - 4 мая"
                          summ="112 500 руб."
                          time="576 акк. часов"
                          img="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                          countUser="2 из 15"
                          linkReg={"/"}
                          linkEnter={"/"}
              />
            </div>
            <div>
              <CourseItem type="card-type--offline"
                          subtitle="Курс косметологии"
                          title="СЕСТРИНСКОЕ ДЕЛО в косметологии"
                          typeName="Оффлайн"
                          dateStart="1 - 4 мая"
                          summ="152 000 руб."
                          time="288 акк. часов"
                          img="https://www.suzan.ru/media/widgetkit/3-f7f4732c5b5bf3377642a63925ade43a.jpg"
                          countUser="2 из 15"
                          linkReg={"/"}
                          linkEnter={"/"}
              />
            </div>
            <div>
              <CourseItem type="card-type--offline"
                          subtitle="Курс косметологии"
                          title="Курс косметик - эстетист"
                          typeName="Оффлайн"
                          dateStart="1 - 4 мая"
                          summ="112 500 руб."
                          time="576 акк. часов"
                          img="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                          countUser="2 из 15"
                          linkReg={"/"}
                          linkEnter={"/"}
              />
            </div>
            <div>
              <CourseItem type="card-type--master-class"
                          subtitle="Курс косметологии"
                          title="Курс косметик - эстетист"
                          typeName="Мастер-класс"
                          dateStart="1 - 4 мая"
                          summ="112 500 руб."
                          time="576 акк. часов"
                          img="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                          countUser="2 из 15"
                          linkReg={"/"}
                          linkEnter={"/"}
              />
            </div>
          </Slider>
        </Row>
      </section>
      
      <section className="section--about container-fluid bg-light pt-5 pb-5">
        <div className="container-md">
          <div className="d-flex container-md">
            <div className="col-12 col-sm-6">&nbsp;</div>
            <div className="col-12 col-sm-6">
              <h1>Школа косметологии</h1>
              <h2>ВЕДУЩИЙ УЧЕБНЫЙ ЦЕНТР ЭСТЕТИЧЕСКОЙ КОСМЕТОЛОГИИ</h2>
              <p>Описание может быть любое.</p>
              <p>Ведущий учебный центр эстетической косметологии. </p>
              <p>Более 5 лет мы проводим курсы сертифицированные курсы профессионального образования в области косметологии и индустрии красоты, здоровья и молодости.</p>
            </div>
          </div>
        </div>
      </section>

      <section className="section--training-cosmetologs container-md pt-5 pb-5">
        <div className="row">
          <h2 className="text-center mb-5 mt-5">Обучение косметологов</h2>
          
          <div className="d-flex flex-wrap">
            <div className="col-md-8 col-sm-6 col-12">
              <div className="card bg-dark text-white">
                <CardImg src="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                      className="card-img"
                      alt=""
                />
                <div className="card-img-overlay d-flex flex-wrap align-items-center">
                  <h5 className="w-100 text-uppercase card-title">курсы косметологии</h5>
                  <ul className="mt-3 card-text">
                    <li>эстетическая косметология</li>
                    <li>инъекционная косметология</li>
                    <li>лазерная косметология</li>
                  </ul>
                </div>
              </div>
            </div>
            
            <div className="col-md-4 col-sm-6 col-12">
              <div className="card bg-dark text-white">
                <CardImg src="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                      className="card-img"
                      alt=""
                />
                <div className="card-img-overlay d-flex align-items-end">
                  <h5 className="card-title text-uppercase">мастер-классы</h5>
                </div>
              </div>
            </div>
          </div>
          
          <div className="d-flex flex-wrap">
            <div className="col-lg-4 col-sm-6 col-12">
              <div className="card bg-dark text-white">
                <CardImg src="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                      className="card-img"
                      alt=""
                />
                <div className="card-img-overlay d-flex flex-wrap align-items-end">
                  <h5 className="w-100 text-uppercase card-title">мастер-классы</h5>
                </div>
              </div>
            </div>
            <div className="col-lg-4 col-sm-6 col-12">
              <div className="card bg-dark text-white">
                <CardImg src="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                      className="card-img"
                      alt=""
                />
                <div className="card-img-overlay d-flex flex-wrap align-items-start">
                  <h5 className="w-100 text-uppercase card-title">расписание</h5>
                </div>
              </div>
            </div>
            <div className="col-lg-4 col-sm-6 col-12">
              <div className="card bg-dark text-white">
                <CardImg src="https://www.suzan.ru/media/widgetkit/apparatnaya-kosmetologiya-5550410aacc0fbf3092e1531e956e72a.jpg"
                      className="card-img"
                      alt=""
                />
                <div className="card-img-overlay d-flex flex-wrap align-items-end">
                  <h5 className="w-100 text-uppercase card-title">Акции</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <section className="section--welcome-models container-fluid bg-light pt-5 pb-5">
        <div className="container-md">
          <div className="d-flex container-md">
            <div className="col-12 col-sm-6">
              <h2 className="mb-5">ВЕДЕМ НАБОР МОДЕЛЕЙ</h2>

              <div className="mt-3 mb-5">
                <p>Мы предлагаем свои услуги для моделей.</p>
                <p>Выберите процедуру или несколько процедур и наш менеджер проконсультирует вас и назовет ближайшую дату, когда вы сможете получить эту процедуру.</p>
              </div>

              <Link href="/">
                <a className="btn bg-primary text-white">
                  Стать моделью
                </a>
              </Link>
            </div>
            
            <div className="col-12 col-sm-6">
              &nbsp;
            </div>
          </div>
        </div>
      </section>

      <section className="section--special-offer container-md mt-5 mb-5 pb-5">
        <Row>
          <h2 className="text-center mb-5">Специальные предложения</h2>
          <Slider {...specialOffer} className="section--special-offer--slick-slider">
            <div>
              <Image
                src={sales_1}
                placeholder="blur"
              />
            </div>
            <div>
              <Image
                src={sales_2}
                placeholder="blur"
              />
            </div>
            <div>
              <Image
                src={sales_3}
                placeholder="blur"
              />
            </div>
            <div>
              <Image
                src={sales_1}
                placeholder="blur"
              />
            </div>
          </Slider>
        </Row>
      </section>
      
      <section className="section--why-we container-fluid bg-light">
        <div className="container-md">
          <div className="row">
            <h2 className="text-center">Почему мы</h2>
          
            <div className="d-flex flex-wrap">
              <div className="card-item col-lg-4 col-sm-6 col-12">
                <div className="card-item--block text-white">
                  <div className="card-item--block-big-numbers">1</div>
                  
                  <div className="card-item--block-img-overlay">
                    <h5 className="w-100 card-title">Преподаватели</h5>

                    <p>Наши преподаватели имеют многолетний опыт в сфере косметологии и совмещают преподовательскую деятельность с практической работой в салонах красоты и других специализированных центрах.</p>
                  </div>
                </div>
              </div>
              <div className="card-item col-lg-4 col-sm-6 col-12">
                <div className="card-item--block">
                  <div className="card-item--block-big-numbers">2</div>
                  
                  <div className="card-item--block-img-overlay">
                    <h5 className="w-100 card-title">Сертификаты</h5>

                    <p>Удостоверение, сертификат и свидетельство полученные у нас по окончанию курсов, работают как лучшая "рекомендация" при приеме на работу</p>
                  </div>
                </div>
              </div>
              <div className="card-item col-lg-4 col-sm-6 col-12">
                <div className="card-item--block">
                  <div className="card-item--block-big-numbers">3</div>
                  
                  <div className="card-item--block-img-overlay">
                    <h5 className="w-100 card-title">Повышение квалификации</h5>

                    <p>Ежегодно, больше 2000 косметологов повышают квалификацию
                       и уровень профессионализма в просторных кабинетах нашего центра.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
